import { FlowShareType } from "./columns";

export const mockFlowSharedData: FlowShareType[] = [
    {
        id: "1",
        flowId: "flow_001",
        userId: "user_001",
        name: "Lead Capture Automation",
        status: "active",
        description: "Tự động thu thập lead từ Facebook Messenger",
        thumbnail: "https://shadcnuikit.com/images/products/01.jpeg",
        downloadCount: 128,
        createdAt: new Date("2025-01-10T08:30:00"),
        updatedAt: new Date("2025-01-20T10:15:00"),
    },
    {
        id: "2",
        flowId: "flow_002",
        userId: "user_002",
        name: "Order Confirmation Bot",
        status: "inactive",
        description: "Xác nhận đơn hàng tự động qua chatbot",
        thumbnail: null,
        downloadCount: 54,
        createdAt: new Date("2025-01-12T14:00:00"),
        updatedAt: new Date("2025-01-18T09:45:00"),
    },
    {
        id: "3",
        flowId: "flow_003",
        userId: "user_003",
        name: "Customer Support FAQ",
        status: "active",
        description: null,
        thumbnail: "https://shadcnuikit.com/images/products/01.jpeg",
        downloadCount: 302,
        createdAt: new Date("2025-01-05T09:20:00"),
        updatedAt: new Date("2025-01-22T16:40:00"),
    },
    {
        id: "4",
        flowId: "flow_004",
        userId: "user_001",
        name: "Booking Appointment Flow",
        status: "active",
        description: "Flow đặt lịch hẹn tự động cho spa / clinic",
        thumbnail: "https://shadcnuikit.com/images/products/01.jpeg",
        downloadCount: 87,
        createdAt: new Date("2025-01-15T11:10:00"),
        updatedAt: new Date("2025-01-21T13:05:00"),
    },
    {
        id: "5",
        flowId: "flow_005",
        userId: "user_004",
        name: "Event Registration Bot",
        status: "inactive",
        description: "Đăng ký sự kiện qua chatbot",
        thumbnail: null,
        downloadCount: 19,
        createdAt: new Date("2025-01-18T17:30:00"),
        updatedAt: new Date("2025-01-23T08:00:00"),
    },
];
