import {
    MessageCircle,
    Zap,
    Type,
    Folder,
    ImageIcon,
    Volume2,
    Video,
    Hash,
    Mail,
    Phone,
    LayoutGrid,
    PlaySquare,
    Clock,
    Variable,
    Code,
    ListChecks,
    PencilLine,
} from "lucide-react";

export const menuData = [
    {
        id: "message",
        category: "message",
        title: "Khối hội thoại",
        icon: MessageCircle,
        color: "#4988C4",
        children: [
            {
                id: "text",
                type: "text",
                title: "Văn bản",
                icon: PencilLine,
                color: "#4988C4",
            },
            {
                id: "image",
                type: "image",
                title: "Hình ảnh",
                icon: ImageIcon,
                color: "#4F8EF7",
            },
            {
                id: "audio",
                type: "audio",
                title: "Âm thanh",
                icon: Volume2,
                color: "#22C55E",
            },
            {
                id: "video",
                type: "video",
                title: "Video",
                icon: Video,
                color: "#A855F7",
            },
            {
                id: "generic_template",
                type: "generic_template",
                title: "Mẫu tổng hợp",
                icon: LayoutGrid,
                color: "#4988C4",
            },
            {
                id: "media_template",
                type: "media_template",
                title: "Mẫu đa phương tiện",
                icon: PlaySquare,
                color: "#4988C4",
            },
        ],
    },
    {
        id: "action",
        category: "action",
        title: "Hành động",
        icon: Zap,
        color: "#FF0000",
        children: [
            {
                id: "delay",
                type: "delay",
                title: "Chờ",
                icon: Clock,
                color: "#FF0000",
            },
            {
                id: "condition",
                type: "condition",
                title: "Điều kiện",
                icon: Code,
                color: "#FF0000",
            },
            {
                id: "set_variable",
                type: "set_variable",
                title: "Gán biến",
                icon: Variable,
                color: "#FF0000",
            },
        ],
    },
    {
        id: "collection",
        category: "collection",
        title: "Thu thập dữ liệu",
        icon: Folder,
        color: "#00C853",
        children: [
            {
                id: "collection-text",
                type: "text",
                title: "Văn bản",
                icon: Type,
                color: "#00C853",
            },
            {
                id: "collection-number",
                type: "number",
                title: "Số",
                icon: Hash, // số / numeric
                color: "#00C853",
            },
            {
                id: "collection-email",
                type: "email",
                title: "Email",
                icon: Mail,
                color: "#00C853",
            },
            {
                id: "collection-phone",
                type: "phone",
                title: "Số điện thoại",
                icon: Phone,
                color: "#00C853",
            },
            {
                id: "collection-custom",
                type: "custom",
                title: "Tùy chỉnh",
                icon: ListChecks,
                color: "#00C853",
            },
        ],
    },
];
